theme: jekyll-theme-tactile
title: Matt Ray's ramblings
description: You've somehow ended up reading Matt Ray's ramblings.
email: matthewhray@gmail.com
twitter_username: mattray
github_username:  mattray
